@startuml
!include clean.skin
"SQL Client" -> "Exasol Core" : Select Request
activate "Exasol Core"
"Exasol Core" -> "Exasol Core": parse
"Exasol Core" -> "Virtual Schema Adapter": getCapabilities
activate "Virtual Schema Adapter"
"Exasol Core" <<-- "Virtual Schema Adapter": list of capabilities
deactivate "Virtual Schema Adapter"
"Exasol Core" -> "Exasol Core": rewrite to remove unsupported parts
"Exasol Core" -> "Virtual Schema Adapter": pushdown("SELECT ...")
activate "Virtual Schema Adapter"
"Exasol Core" <<-- "Virtual Schema Adapter": "IMPORT FROM JDBC ..."
deactivate "Virtual Schema Adapter"
"Exasol Core" -> Importer: IMPORT FROM JDBC ...
activate "Importer"
"Exasol Core" <<-- Importer: rows
deactivate "Importer"
"Exasol Core" -> "Exasol Core": post process
"SQL Client" <<-- "Exasol Core": rows
deactivate "Exasol Core"
@enduml
